spring:
  redis:
    host: localhost
    port: 6379
    database: 0

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: h2
